(** Expect-test workflow.

    The [expect_test_helper] library provides the snapshot-testing plumbing
    shared by the parser and semantics test suites. Each suite is built around a
    list of named test groups; running the executable with a group name on the
    command line produces a snapshot block, and running it with [--gen-rules]
    emits the matching set of dune [(diff)] rules.

    This is a brief operator's guide; the values below are the API.

    {1 Where things live}

    - [src/parser/test/test.ml], [src/parser/test/test_tables.ml] — parser test
      cases; [src/parser/test/odoc_parser_test_main.ml] — parser dispatcher
    - [test/model/semantics/odoc_semantic_test.ml] — semantics tests
    - [<test-dir>/expected/<group>.expected] — the committed snapshots, compared
      by [dune (diff)] under the [runtest] alias
    - [<test-dir>/dune.inc] — generated by [<exe> --gen-rules]; one [(diff)]
      rule per group. Committed; checked under [runtest]; updated by
      [dune promote].

    {1 Common workflows}

    {2 Adding a case to an existing group}

    Open the relevant test module ([src/parser/test/test.ml] for the parser,
    [test/model/semantics/odoc_semantic_test.ml] for the semantics) and add a
    binding inside the group's [let module ... struct ... end]:

    {[
      let my_new_case = test "{some odoc markup}"
    ]}

    The binding name is documentation; only the group name appears in the
    snapshot key. Then regenerate the expected output:

    {@sh[
      dune runtest <test-dir> --auto-promote
    ]}

    Or run without [--auto-promote] to inspect the diff first and promote once
    happy.

    {2 Adding a new group}

    {ol
     {- Define the group function in the test module (parser:
        [src/parser/test/test.ml]; semantics:
        [test/model/semantics/odoc_semantic_test.ml]):

        {[
          let my_new_group () =
            let module My_new_group = struct
              let case_one = test "..."
              let case_two = test "..."
            end in
            ()
        ]}
     }
     {- Register it in the dispatcher's [groups] list (parser:
        [odoc_parser_test_main.ml]; semantics: bottom of
        [odoc_semantic_test.ml]):

        {[
          "my_new_group", Test.my_new_group
        ]}
     }
     {- Seed the expected file and regenerate the dune rules:

        {@sh[
          touch <test-dir>/expected/my_new_group.expected
          dune build --auto-promote      # updates dune.inc
          dune runtest --auto-promote    # fills in the expected file
        ]}
     }
    }

    {2 Removing or renaming a group}

    Edit the group function and the [groups] list together; delete the stale
    [expected/<old_name>.expected]; then [dune build --auto-promote] updates
    [dune.inc]. *)

val print : input:string -> output:string -> unit
(** [print ~input ~output] frames a pair of strings with [--- input ---] /
    [--- output ---] headers and trailing newlines, writing to stdout. *)

val expect : input:string -> (Format.formatter -> unit) -> unit
(** [expect ~input format_output] is like {!print}, but the output is produced
    by a [Format.formatter -> unit] callback. Useful when the serializer writes
    through {!Format}. *)

val lexing_position :
  ?filename:string -> ?line:int -> ?column:int -> unit -> Lexing.position
(** [lexing_position ?filename ?line ?column ()] builds a [Lexing.position] with
    sensible defaults ([filename = "f.ml"], [line = 1], [column = 0]). *)

val run : ?package:string -> (string * (unit -> unit)) list -> unit
(** [run ?package groups] is the argv dispatcher. With [--gen-rules], it emits
    the per-group dune rules to stdout (with [(package ...)] if supplied);
    otherwise it looks up [argv.(1)] in [groups] and runs it. *)
