(* generated by dune *)

(** @canonical Odoc_latex.Generator *)
module Generator = Odoc_latex__Generator

(** @canonical Odoc_latex.Raw *)
module Raw = Odoc_latex__Raw

(** @canonical Odoc_latex.Types *)
module Types = Odoc_latex__Types
