  $ odoc support-files -o with-theme
  $ find with-theme | sort
  with-theme
  with-theme/fonts
  with-theme/fonts/KaTeX_AMS-Regular.woff2
  with-theme/fonts/KaTeX_Caligraphic-Bold.woff2
  with-theme/fonts/KaTeX_Caligraphic-Regular.woff2
  with-theme/fonts/KaTeX_Fraktur-Bold.woff2
  with-theme/fonts/KaTeX_Fraktur-Regular.woff2
  with-theme/fonts/KaTeX_Main-Bold.woff2
  with-theme/fonts/KaTeX_Main-BoldItalic.woff2
  with-theme/fonts/KaTeX_Main-Italic.woff2
  with-theme/fonts/KaTeX_Main-Regular.woff2
  with-theme/fonts/KaTeX_Math-BoldItalic.woff2
  with-theme/fonts/KaTeX_Math-Italic.woff2
  with-theme/fonts/KaTeX_SansSerif-Bold.woff2
  with-theme/fonts/KaTeX_SansSerif-Italic.woff2
  with-theme/fonts/KaTeX_SansSerif-Regular.woff2
  with-theme/fonts/KaTeX_Script-Regular.woff2
  with-theme/fonts/KaTeX_Size1-Regular.woff2
  with-theme/fonts/KaTeX_Size2-Regular.woff2
  with-theme/fonts/KaTeX_Size3-Regular.woff2
  with-theme/fonts/KaTeX_Size4-Regular.woff2
  with-theme/fonts/KaTeX_Typewriter-Regular.woff2
  with-theme/fonts/fira-mono-v14-latin-500.woff2
  with-theme/fonts/fira-mono-v14-latin-regular.woff2
  with-theme/fonts/fira-sans-v17-latin-500.woff2
  with-theme/fonts/fira-sans-v17-latin-500italic.woff2
  with-theme/fonts/fira-sans-v17-latin-700.woff2
  with-theme/fonts/fira-sans-v17-latin-700italic.woff2
  with-theme/fonts/fira-sans-v17-latin-italic.woff2
  with-theme/fonts/fira-sans-v17-latin-regular.woff2
  with-theme/fonts/noticia-text-v15-latin-700.woff2
  with-theme/fonts/noticia-text-v15-latin-italic.woff2
  with-theme/fonts/noticia-text-v15-latin-regular.woff2
  with-theme/highlight.pack.js
  with-theme/katex.min.css
  with-theme/katex.min.js
  with-theme/odoc.css
  with-theme/odoc_search.js

  $ odoc support-files --without-theme -o without-theme
  $ find without-theme | sort
  without-theme
  without-theme/fonts
  without-theme/fonts/KaTeX_AMS-Regular.woff2
  without-theme/fonts/KaTeX_Caligraphic-Bold.woff2
  without-theme/fonts/KaTeX_Caligraphic-Regular.woff2
  without-theme/fonts/KaTeX_Fraktur-Bold.woff2
  without-theme/fonts/KaTeX_Fraktur-Regular.woff2
  without-theme/fonts/KaTeX_Main-Bold.woff2
  without-theme/fonts/KaTeX_Main-BoldItalic.woff2
  without-theme/fonts/KaTeX_Main-Italic.woff2
  without-theme/fonts/KaTeX_Main-Regular.woff2
  without-theme/fonts/KaTeX_Math-BoldItalic.woff2
  without-theme/fonts/KaTeX_Math-Italic.woff2
  without-theme/fonts/KaTeX_SansSerif-Bold.woff2
  without-theme/fonts/KaTeX_SansSerif-Italic.woff2
  without-theme/fonts/KaTeX_SansSerif-Regular.woff2
  without-theme/fonts/KaTeX_Script-Regular.woff2
  without-theme/fonts/KaTeX_Size1-Regular.woff2
  without-theme/fonts/KaTeX_Size2-Regular.woff2
  without-theme/fonts/KaTeX_Size3-Regular.woff2
  without-theme/fonts/KaTeX_Size4-Regular.woff2
  without-theme/fonts/KaTeX_Typewriter-Regular.woff2
  without-theme/fonts/fira-mono-v14-latin-500.woff2
  without-theme/fonts/fira-mono-v14-latin-regular.woff2
  without-theme/fonts/fira-sans-v17-latin-500.woff2
  without-theme/fonts/fira-sans-v17-latin-500italic.woff2
  without-theme/fonts/fira-sans-v17-latin-700.woff2
  without-theme/fonts/fira-sans-v17-latin-700italic.woff2
  without-theme/fonts/fira-sans-v17-latin-italic.woff2
  without-theme/fonts/fira-sans-v17-latin-regular.woff2
  without-theme/fonts/noticia-text-v15-latin-700.woff2
  without-theme/fonts/noticia-text-v15-latin-italic.woff2
  without-theme/fonts/noticia-text-v15-latin-regular.woff2
  without-theme/highlight.pack.js
  without-theme/katex.min.css
  without-theme/katex.min.js
  without-theme/odoc_search.js

