  $ find ../docs/odoc/base/ -name '*.odocl' -exec basename '{}' ';' | sort
  base.odocl
  base__.odocl
  base__Applicative.odocl
  base__Applicative_intf.odocl
  base__Array.odocl
  base__Array0.odocl
  base__Array_permute.odocl
  base__Avltree.odocl
  base__Backtrace.odocl
  base__Binary_search.odocl
  base__Binary_searchable.odocl
  base__Binary_searchable_intf.odocl
  base__Blit.odocl
  base__Blit_intf.odocl
  base__Bool.odocl
  base__Bool0.odocl
  base__Buffer.odocl
  base__Buffer_intf.odocl
  base__Bytes.odocl
  base__Bytes0.odocl
  base__Bytes_tr.odocl
  base__Char.odocl
  base__Char0.odocl
  base__Comparable.odocl
  base__Comparable_intf.odocl
  base__Comparator.odocl
  base__Comparisons.odocl
  base__Container.odocl
  base__Container_intf.odocl
  base__Either.odocl
  base__Either0.odocl
  base__Either_intf.odocl
  base__Equal.odocl
  base__Error.odocl
  base__Exn.odocl
  base__Field.odocl
  base__Fieldslib.odocl
  base__Float.odocl
  base__Float0.odocl
  base__Floatable.odocl
  base__Fn.odocl
  base__Formatter.odocl
  base__Globalize.odocl
  base__Hash.odocl
  base__Hash_intf.odocl
  base__Hash_set.odocl
  base__Hash_set_intf.odocl
  base__Hashable.odocl
  base__Hashable_intf.odocl
  base__Hasher.odocl
  base__Hashtbl.odocl
  base__Hashtbl_intf.odocl
  base__Hex_lexer.odocl
  base__Identifiable.odocl
  base__Identifiable_intf.odocl
  base__Import.odocl
  base__Import0.odocl
  base__Indexed_container.odocl
  base__Indexed_container_intf.odocl
  base__Info.odocl
  base__Info_intf.odocl
  base__Int.odocl
  base__Int0.odocl
  base__Int32.odocl
  base__Int63.odocl
  base__Int63_emul.odocl
  base__Int64.odocl
  base__Int_conversions.odocl
  base__Int_intf.odocl
  base__Int_math.odocl
  base__Intable.odocl
  base__Invariant.odocl
  base__Invariant_intf.odocl
  base__Lazy.odocl
  base__Linked_queue.odocl
  base__Linked_queue0.odocl
  base__List.odocl
  base__List0.odocl
  base__List1.odocl
  base__Map.odocl
  base__Map_intf.odocl
  base__Maybe_bound.odocl
  base__Monad.odocl
  base__Monad_intf.odocl
  base__Nativeint.odocl
  base__Nothing.odocl
  base__Obj_array.odocl
  base__Obj_local.odocl
  base__Option.odocl
  base__Option_array.odocl
  base__Or_error.odocl
  base__Ordered_collection_common.odocl
  base__Ordered_collection_common0.odocl
  base__Ordering.odocl
  base__Poly0.odocl
  base__Popcount.odocl
  base__Pow_overflow_bounds.odocl
  base__Ppx_compare_lib.odocl
  base__Ppx_enumerate_lib.odocl
  base__Ppx_hash_lib.odocl
  base__Pretty_printer.odocl
  base__Printf.odocl
  base__Queue.odocl
  base__Queue_intf.odocl
  base__Random.odocl
  base__Random_repr.odocl
  base__Ref.odocl
  base__Result.odocl
  base__Sequence.odocl
  base__Set.odocl
  base__Set_intf.odocl
  base__Sexp.odocl
  base__Sexp_with_comparable.odocl
  base__Sexpable.odocl
  base__Sign.odocl
  base__Sign0.odocl
  base__Sign_or_nan.odocl
  base__Source_code_position.odocl
  base__Source_code_position0.odocl
  base__Stack.odocl
  base__Stack_intf.odocl
  base__Staged.odocl
  base__String.odocl
  base__String0.odocl
  base__Stringable.odocl
  base__Sys.odocl
  base__Sys0.odocl
  base__T.odocl
  base__Type_equal.odocl
  base__Uchar.odocl
  base__Uchar0.odocl
  base__Uniform_array.odocl
  base__Unit.odocl
  base__Variant.odocl
  base__Variantslib.odocl
  base__With_return.odocl
  base__Word_size.odocl
  base_internalhash_types.odocl
  caml.odocl
  md5_lib.odocl
  page-index.odocl
  shadow_stdlib.odocl
