(* generated by dune *)

(** @canonical Odoc_json_index.Json_display *)
module Json_display = Odoc_json_index__Json_display

(** @canonical Odoc_json_index.Json_search *)
module Json_search = Odoc_json_index__Json_search
