(* generated by dune *)

(** @canonical Odoc_utils.Json *)
module Json = Odoc_utils__Json

(** @canonical Odoc_utils.Odoc_list *)
module Odoc_list = Odoc_utils__Odoc_list

(** @canonical Odoc_utils.Tree *)
module Tree = Odoc_utils__Tree

module Odoc_utils__ = struct end
[@@deprecated "this module is shadowed"]
