(* generated by dune *)

(** @canonical Odoc_index.Entry *)
module Entry = Odoc_index__Entry

(** @canonical Odoc_index.In_progress *)
module In_progress = Odoc_index__In_progress

(** @canonical Odoc_index.Skeleton *)
module Skeleton = Odoc_index__Skeleton

(** @canonical Odoc_index.Skeleton_of *)
module Skeleton_of = Odoc_index__Skeleton_of

module Odoc_index__ = struct end
[@@deprecated "this module is shadowed"]
