(* generated by dune *)

(** @canonical Odoc_model_desc.Comment_desc *)
module Comment_desc = Odoc_model_desc__Comment_desc

(** @canonical Odoc_model_desc.Lang_desc *)
module Lang_desc = Odoc_model_desc__Lang_desc

(** @canonical Odoc_model_desc.Paths_desc *)
module Paths_desc = Odoc_model_desc__Paths_desc

(** @canonical Odoc_model_desc.Type_desc *)
module Type_desc = Odoc_model_desc__Type_desc
